// -----------------------------------------------------------------------------
// fft_twiddle_rom — the twiddle coefficient memory of one multiplier stage.
//
// SPEC 7.2: "Twiddle ROMs inferred into memory." This module is the inference
// site, and it is the ONLY one in the FFT: every multiplier stage — the
// radix-2^2 stages and the DIT merge alike — instantiates this and differs only
// in its parameters.
//
// -----------------------------------------------------------------------------
// Contents
// -----------------------------------------------------------------------------
// The ROM is addressed by the SAMPLE POSITION, not by a computed exponent. The
// exponent arithmetic of the radix-2^2 decomposition (fft_pkg::fft_r22_tw_exp)
// and the bit-reversal of the merge (fft_pkg::fft_dit_tw_exp) are performed at
// ELABORATION time, once per address, and the answer is baked into the table.
// So the hardware holds an address counter and a memory and nothing else — no
// multiplier for the exponent, no bit-reverse network, no case tree — and the
// index arithmetic exists in exactly one place, fft_pkg, where the C++ model
// mirrors it.
//
// The values themselves come from rtl/fft/generated/fft_twiddle_pkg.sv, the
// committed table generated by model/python/gen_fft_twiddles.py. Nothing here
// evaluates a trigonometric function: see that script's header for why a table
// computed at elaboration time by three different libm implementations is a
// correctness risk that cannot be detected from inside a simulation.
//
// KIND selects which of the two addressings the table is built with:
//
//   "R22"  a radix-2^2 stage's twiddles, W_L^{n3(k1+2k2)}, addressed by the low
//          log2(L) bits of the position. DEPTH = L.
//   "DIT"  a merge level's twiddles, W_{M*2^(level+1)}^{bitrev(j)}, addressed by
//          the output beat index j. DEPTH = M (= 2^N_LANE).
//
// -----------------------------------------------------------------------------
// Inference and latency (SPEC 23: registers on both sides of a memory)
// -----------------------------------------------------------------------------
//   OUT_REG = 0   synchronous read, one cycle: the memory's input register.
//   OUT_REG = 1   plus the memory's output register, two cycles. The default,
//                 because an M20K read that has to reach a DSP input in the same
//                 cycle is precisely the path SPEC 23 asks to be broken.
//
// LATENCY is exported as a localparam and read back by the stage that
// instantiates this, so the data-alignment delay is derived from the memory's
// own shape rather than from a number written twice.
//
// Lint contract: clean under `verilator --lint-only --Wall` with no waiver.
// -----------------------------------------------------------------------------

`default_nettype none

module fft_twiddle_rom
  import fxp_pkg::fxp_complex_t;
  import fft_pkg::*;
#(
    // "R22" or "DIT".
    parameter string       KIND    = "R22",

    // Address width. DEPTH = 2^ADDR_W, and the meaning of an address is KIND's.
    parameter int unsigned ADDR_W  = 5,

    // R22: log2 of the group's sub-transform length L. Unused for DIT.
    parameter int unsigned L2L     = 5,

    // DIT: log2 of the per-lane transform length, and the merge level.
    // Unused for R22.
    parameter int unsigned N_LANE  = 5,
    parameter int unsigned LEVEL   = 0,

    // 1: add the memory output register (two-cycle read). See above.
    parameter int unsigned OUT_REG = 1,

    // "AUTO" | "M20K" | "MLAB" | "LOGIC" — SPEC 18 memory-geometry axis.
    parameter string       STYLE   = "AUTO"
) (
    input  wire                clk,
    input  wire                en,
    input  wire [ADDR_W-1:0]   addr,
    output wire fxp_complex_t  tw
);

  localparam int unsigned DEPTH   = 1 << ADDR_W;
  localparam int unsigned WORD_W  = $bits(fxp_complex_t);

  typedef logic [WORD_W-1:0] tw_word_t;
  typedef tw_word_t          tw_table_t [DEPTH];

  // ---------------------------------------------------------------------------
  // Elaboration-time table construction
  //
  // Pure function of the parameters and of the committed master table. Every
  // address is resolved here and nothing survives into the hardware but the
  // resulting constants.
  // ---------------------------------------------------------------------------
  function automatic tw_table_t build_table();
    tw_table_t      t;
    fxp_complex_t   c;
    for (int unsigned a = 0; a < DEPTH; a++) begin
      c    = (KIND == "DIT") ? fft_dit_tw(fft_uint_t'(N_LANE), fft_uint_t'(LEVEL), a)
                             : fft_r22_tw(fft_uint_t'(L2L), a);
      t[a] = tw_word_t'(c);
    end
    return t;
  endfunction

  localparam tw_table_t TW_TABLE = build_table();

`ifndef SYNTHESIS
  initial begin
    if (KIND != "R22" && KIND != "DIT") begin
      $fatal(1, "fft_twiddle_rom: KIND=\"%s\" is not \"R22\" or \"DIT\"", KIND);
    end
    if (OUT_REG > 1) begin
      $fatal(1, "fft_twiddle_rom: OUT_REG=%0d is not 0 or 1", OUT_REG);
    end
    if (KIND == "R22" && ADDR_W != L2L) begin
      $fatal(1, "fft_twiddle_rom(R22): ADDR_W=%0d must equal L2L=%0d",
             ADDR_W, L2L);
    end
    if (KIND == "DIT" && ADDR_W != N_LANE) begin
      $fatal(1, "fft_twiddle_rom(DIT): ADDR_W=%0d must equal N_LANE=%0d",
             ADDR_W, N_LANE);
    end
    if (WORD_W != int'(fft_twiddle_pkg::FFT_TW_W)) begin
      $fatal(1, "fft_twiddle_rom: complex word is %0d bits, the table is %0d",
             WORD_W, fft_twiddle_pkg::FFT_TW_W);
    end
    // The read latency this memory presents must be the one fft_pkg tells the
    // stages to align against; the two are separated by a parameter, so they are
    // checked rather than assumed.
    if (fft_tw_rom_latency(fft_uint_t'(OUT_REG)) != fft_uint_t'(1 + OUT_REG)) begin
      $fatal(1, "fft_twiddle_rom: fft_pkg says latency %0d, this memory has %0d",
             fft_tw_rom_latency(fft_uint_t'(OUT_REG)), 1 + OUT_REG);
    end
  end
`endif

  // ---------------------------------------------------------------------------
  // The memory. One synchronous read port; the four branches differ only in the
  // placement attribute (see fft_delay_line for the same arrangement).
  // ---------------------------------------------------------------------------
  tw_word_t rd_q;

  if (STYLE == "M20K") begin : g_m20k
    (* romstyle = "M20K" *) tw_word_t rom [DEPTH] = TW_TABLE;
    always_ff @(posedge clk) if (en) rd_q <= rom[addr];
  end else if (STYLE == "MLAB") begin : g_mlab
    (* romstyle = "MLAB" *) tw_word_t rom [DEPTH] = TW_TABLE;
    always_ff @(posedge clk) if (en) rd_q <= rom[addr];
  end else if (STYLE == "LOGIC") begin : g_logic
    (* romstyle = "logic" *) tw_word_t rom [DEPTH] = TW_TABLE;
    always_ff @(posedge clk) if (en) rd_q <= rom[addr];
  end else begin : g_auto
    tw_word_t rom [DEPTH] = TW_TABLE;
    always_ff @(posedge clk) if (en) rd_q <= rom[addr];
  end

  tw_word_t out_c;

  if (OUT_REG != 0) begin : g_out_reg
    tw_word_t out_q;
    always_ff @(posedge clk) if (en) out_q <= rd_q;
    assign out_c = out_q;
  end else begin : g_no_out_reg
    assign out_c = rd_q;
  end

  assign tw = fxp_complex_t'(out_c);

endmodule : fft_twiddle_rom

`default_nettype wire
